### ISSUE TITLE
Upgrade the simple text consumer

### ISSUE THREAD

**Issue by dbgjerez** [dbgjerez/quarkus-kafka#1]
Upgrade the java version, Quarkus, etc.

https://github.com/dbgjerez/quarkus-kafka/blob/975c5e94c49d3a053bfc45e4becdfd275302ba76/simple-kafka-consumer/pom.xml#L15

**Comment by JuanmaBM** [comment]
Upgrades quarkus verstion to use OpenJDK 17

**Comment by dbgjerez** [comment]
I think we should upgrade quarkus to 2.16 too

**Comment by JuanmaBM** [comment]
Quarkus version upgraded
