### ISSUE TITLE
Upgrade the publisher simple text application

### ISSUE THREAD

**Issue by dbgjerez** [dbgjerez/quarkus-kafka#2]
Upgrade the Java version, quarkus, etc

https://github.com/dbgjerez/quarkus-kafka/blob/975c5e94c49d3a053bfc45e4becdfd275302ba76/simple-kafka-producer/pom.xml#L15

**Comment by JuanmaBM** [comment]
Upgrades quarkus verstion to use OpenJDK 17

**Comment by dbgjerez** [comment]
I think we should upgrade quarkus to 2.16 too

**Comment by JuanmaBM** [comment]
Quarkus version upgraded
